local opt = vim.opt

opt.cmdheight = 1
opt.showtabline = 0 -- always see tab lines
opt.expandtab = true
opt.shiftwidth = 2
opt.tabstop = 2
opt.number = true -- see lines' number
opt.numberwidth = 4
opt.title = true
opt.scrolloff = 8 -- minimal number of characters left before the end of the window
opt.mouse = "a"
opt.cursorline = true
opt.sidescrolloff = 8
opt.smartindent = true
opt.termguicolors = true
opt.wrap = true
opt.linebreak = true
opt.clipboard = "unnamedplus"
