name: Linter

on: [push]

jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lunarmodules/luacheck@v1
        with:
          args: init.lua lua/*
