name: Linter

on: [push]

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"
      - uses: leafo/gh-actions-luarocks@v4

      - name: Install linter
        run: luarocks install luacheck
      - name: Run linter
        run: luacheck *.lua lua/* --globals vim client
  stylua-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run stylua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
